<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CetiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([
                ['city'=> 'Aïn Harrouda', 'region_id'=>6],
                ['city'=> 'Ben Yakhlef', 'region_id'=>6],
                ['city'=> 'Bouskoura', 'region_id'=>6],
                ['city'=> 'Casablanca', 'region_id'=>6],
                ['city'=> 'Médiouna', 'region_id'=>6],
                ['city'=> 'Mohammadia', 'region_id'=>6],
                ['city'=> 'Tit Mellil', 'region_id'=>6],
                ['city'=> 'Ben Yakhlef', 'region_id'=>6],
                ['city'=> 'Bejaâd', 'region_id'=>5],
                ['city'=> 'Ben Ahmed', 'region_id'=>6],
                ['city'=> 'Benslimane', 'region_id'=>6],
                ['city'=> 'Berrechid', 'region_id'=>6],
                ['city'=> 'Boujniba', 'region_id'=>5],
                ['city'=> 'Boulanouare', 'region_id'=>5],
                ['city'=> 'Bouznika', 'region_id'=>6],
                ['city'=> 'Deroua', 'region_id'=>6],
                ['city'=> 'El Borouj', 'region_id'=>6],
                ['city'=> 'El Gara', 'region_id'=>6],
                ['city'=> 'Guisser', 'region_id'=>6],
                ['city'=> 'Hattane', 'region_id'=>5],
                ['city'=> 'Khouribga', 'region_id'=>5],
                ['city'=> 'Loulad', 'region_id'=>6],
                ['city'=> 'Oued Zem', 'region_id'=>5],
                ['city'=> 'Oulad Abbou', 'region_id'=>6],
                ['city'=> 'Oulad H Riz Sahel', 'region_id'=>6],
                ['city'=> 'Oulad M rah', 'region_id'=>6],
                ['city'=> 'Oulad Saïd', 'region_id'=>6],
                ['city'=> 'Oulad Sidi Ben Daoud', 'region_id'=>6],
                ['city'=> 'Ras El Aïn', 'region_id'=>6],
                ['city'=> 'Settat', 'region_id'=>6],
                ['city'=> 'Sidi Rahhal Chataï', 'region_id'=>6],
                ['city'=> 'Soualem', 'region_id'=>6],
                ['city'=> 'Azemmour', 'region_id'=>6],
                ['city'=> 'Bir Jdid', 'region_id'=>6],
                ['city'=> 'Bouguedra', 'region_id'=>7],
                ['city'=> 'Echemmaia', 'region_id'=>7],
                ['city'=> 'El Jadida', 'region_id'=>6],
                ['city'=> 'Hrara', 'region_id'=>7],
                ['city'=> 'Ighoud', 'region_id'=>7],
                ['city'=> 'Jamâat Shaim', 'region_id'=>7],
                ['city'=> 'Jorf Lasfar', 'region_id'=>6],
                ['city'=> 'Khemis Zemamra', 'region_id'=>6],
                ['city'=> 'Laaounate', 'region_id'=>6],
                ['city'=> 'Moulay Abdallah', 'region_id'=>6],
                ['city'=> 'Oualidia', 'region_id'=>6],
                ['city'=> 'Oulad Amrane', 'region_id'=>6],
                ['city'=> 'Oulad Frej', 'region_id'=>6],
                ['city'=> 'Oulad Ghadbane', 'region_id'=>6],
                ['city'=> 'Safi', 'region_id'=>7],
                ['city'=> 'Sebt El Maârif', 'region_id'=>6],
                ['city'=> 'Sebt Gzoula', 'region_id'=>7],
                ['city'=> 'Sidi Ahmed', 'region_id'=>7],
                ['city'=> 'Sidi Ali Ban Hamdouche', 'region_id'=>6],
                ['city'=> 'Sidi Bennour', 'region_id'=>6],
                ['city'=> 'Sidi Bouzid', 'region_id'=>6],
                ['city'=> 'Sidi Smaïl', 'region_id'=>6],
                ['city'=> 'Youssoufia', 'region_id'=>7],
                ['city'=> 'Fès', 'region_id'=>3],
                ['city'=> 'Aïn Cheggag', 'region_id'=>3],
                ['city'=> 'Bhalil', 'region_id'=>3],
                ['city'=> 'Boulemane', 'region_id'=>3],
                ['city'=> 'El Menzel', 'region_id'=>3],
                ['city'=> 'Guigou', 'region_id'=>3],
                ['city'=> 'Imouzzer Kandar', 'region_id'=>3],
                ['city'=> 'Imouzzer Marmoucha', 'region_id'=>3],
                ['city'=> 'Missour', 'region_id'=>3],
                ['city'=> 'Moulay Yaâcoub', 'region_id'=>3],
                ['city'=> 'Ouled Tayeb', 'region_id'=>3],
                ['city'=> 'Outat El Haj', 'region_id'=>3],
                ['city'=> 'Ribate El Kheir', 'region_id'=>3],
                ['city'=> 'Séfrou', 'region_id'=>3],
                ['city'=> 'Skhinate', 'region_id'=>3],
                ['city'=> 'Tafajight', 'region_id'=>3],
                ['city'=> 'Arbaoua', 'region_id'=>4],
                ['city'=> 'Aïn Dorij', 'region_id'=>1],
                ['city'=> 'Dar Gueddari', 'region_id'=>4],
                ['city'=> 'Had Kourt', 'region_id'=>4],
                ['city'=> 'Jorf El Melha', 'region_id'=>4],
                ['city'=> 'Kénitra', 'region_id'=>4],
                ['city'=> 'Khenichet', 'region_id'=>4],
                ['city'=> 'Lalla Mimouna', 'region_id'=>4],
                ['city'=> 'Mechra Bel Ksiri', 'region_id'=>4],
                ['city'=> 'Mehdia', 'region_id'=>4],
                ['city'=> 'Moulay Bousselham', 'region_id'=>4],
                ['city'=> 'Sidi Allal Tazi', 'region_id'=>4],
                ['city'=> 'Sidi Kacem', 'region_id'=>4],
                ['city'=> 'Sidi Slimane', 'region_id'=>4],
                ['city'=> 'Sidi Taibi', 'region_id'=>4],
                ['city'=> 'Sidi Yahya El Gharb', 'region_id'=>4],
                ['city'=> 'Souk El Arbaa', 'region_id'=>4],
                ['city'=> 'Akka', 'region_id'=>9],
                ['city'=> 'Assa', 'region_id'=>10],
                ['city'=> 'Bouizakarne', 'region_id'=>10],
                ['city'=> 'El Ouatia', 'region_id'=>10],
                ['city'=> 'Es-Semara', 'region_id'=>11],
                ['city'=> 'Fam El Hisn', 'region_id'=>9],
                ['city'=> 'Foum Zguid', 'region_id'=>9],
                ['city'=> 'Guelmim', 'region_id'=>10],
                ['city'=> 'Taghjijt', 'region_id'=>10],
                ['city'=>  'Tan-Tan', 'region_id'=>10],
                ['city'=>  'Tata', 'region_id'=>9],
                ['city'=>  'Zag', 'region_id'=>10],
                ['city'=>  'Marrakech', 'region_id'=>7],
                ['city'=>  'Ait Daoud', 'region_id'=>7],
                ['city'=>  'Amizmiz', 'region_id'=>7],
                ['city'=>  'Assahrij', 'region_id'=>7],
                ['city'=>  'Aït Ourir', 'region_id'=>7],
                ['city'=>  'Ben Guerir', 'region_id'=>7],
                ['city'=>  'Chichaoua', 'region_id'=>7],
                ['city'=>  'El Hanchane', 'region_id'=>7],
                ['city'=>  'El Kelaâ des Sraghna', 'region_id'=>7],
                ['city'=>  'Essaouira', 'region_id'=>7],
                ['city'=>  'Fraïta', 'region_id'=>7],
                ['city'=>  'Ghmate', 'region_id'=>7],
                ['city'=>  'Ighounane', 'region_id'=>8],
                ['city'=>  'Imintanoute', 'region_id'=>7],
                ['city'=>  'Kattara', 'region_id'=>7],
                ['city'=>  'Lalla Takerkoust', 'region_id'=>7],
                ['city'=>  'Loudaya', 'region_id'=>7],
                ['city'=>  'Lâattaouia', 'region_id'=>7],
                ['city'=>  'Moulay Brahim', 'region_id'=>7],
                ['city'=>  'Mzouda', 'region_id'=>7],
                ['city'=>  'Ounagha', 'region_id'=>7],
                ['city'=>  'Sid LMokhtar', 'region_id'=>7],
                ['city'=>  'Sid Zouin', 'region_id'=>7],
                ['city'=>  'Sidi Abdallah Ghiat', 'region_id'=>7],
                ['city'=>  'Sidi Bou Othmane', 'region_id'=>7],
                ['city'=>  'Sidi Rahhal', 'region_id'=>7],
                ['city'=>  'Skhour Rehamna', 'region_id'=>7],
                ['city'=>  'Smimou', 'region_id'=>7],
                ['city'=>  'Tafetachte', 'region_id'=>7],
                ['city'=>  'Tahannaout', 'region_id'=>7],
                ['city'=>  'Talmest', 'region_id'=>7],
                ['city'=>  'Tamallalt', 'region_id'=>7],
                ['city'=>  'Tamanar', 'region_id'=>7],
                ['city'=>  'Tamansourt', 'region_id'=>7],
                ['city'=>  'Tameslouht', 'region_id'=>7],
                ['city'=>  'Tanalt', 'region_id'=>9],
                ['city'=>  'Zeubelemok', 'region_id'=>7],
                ['city'=>  'Meknès‎', 'region_id'=>3],
                ['city'=>  'Khénifra', 'region_id'=>5],
                ['city'=>  'Agourai', 'region_id'=>3],
                ['city'=>  'Ain Taoujdate', 'region_id'=>3],
                ['city'=>  'MyAliCherif', 'region_id'=>8],
                ['city'=>  'Rissani', 'region_id'=>8],
                ['city'=>  'Amalou Ighriben', 'region_id'=>5],
                ['city'=>  'Aoufous', 'region_id'=>8],
                ['city'=>  'Arfoud', 'region_id'=>8],
                ['city'=>  'Azrou', 'region_id'=>3],
                ['city'=>  'Aïn Jemaa', 'region_id'=>3],
                ['city'=>  'Aïn Karma', 'region_id'=>3],
                ['city'=>  'Aïn Leuh', 'region_id'=>3],
                ['city'=>  'Aït Boubidmane', 'region_id'=>3],
                ['city'=>  'Aït Ishaq', 'region_id'=>5],
                ['city'=>  'Boudnib', 'region_id'=>8],
                ['city'=>  'Boufakrane', 'region_id'=>3],
                ['city'=>  'Boumia', 'region_id'=>8],
                ['city'=>  'El Hajeb', 'region_id'=>3],
                ['city'=>  'Elkbab', 'region_id'=>5],
                ['city'=>  'Er-Rich', 'region_id'=>5],
                ['city'=>  'Errachidia', 'region_id'=>8],
                ['city'=>  'Gardmit', 'region_id'=>8],
                ['city'=>  'Goulmima', 'region_id'=>8],
                ['city'=>  'Gourrama', 'region_id'=>8],
                ['city'=>  'Had Bouhssoussen', 'region_id'=>5],
                ['city'=>  'Haj Kaddour', 'region_id'=>3],
                ['city'=>  'Ifrane', 'region_id'=>3],
                ['city'=>  'Itzer', 'region_id'=>8],
                ['city'=>  'Jorf', 'region_id'=>8],
                ['city'=>  'Kehf Nsour', 'region_id'=>5],
                ['city'=>  'Kerrouchen', 'region_id'=>5],
                ['city'=>  'Mhaya', 'region_id'=>3],
                ['city'=>  'Mrirt', 'region_id'=>5],
                ['city'=>  'Midelt', 'region_id'=>8],
                ['city'=>  'Moulay Ali Cherif', 'region_id'=>8],
                ['city'=>  'Moulay Bouazza', 'region_id'=>5],
                ['city'=>  'Moulay Idriss Zerhoun', 'region_id'=>3],
                ['city'=>  'Moussaoua', 'region_id'=>3],
                ['city'=>  'NZalat Bni Amar', 'region_id'=>3],
                ['city'=>  'Ouaoumana', 'region_id'=>5],
                ['city'=>  'Oued Ifrane', 'region_id'=>3],
                ['city'=>  'Sabaa Aiyoun', 'region_id'=>3],
                ['city'=>  'Sebt Jahjouh', 'region_id'=>3],
                ['city'=>  'Sidi Addi', 'region_id'=>3],
                ['city'=>  'Tichoute', 'region_id'=>8],
                ['city'=>  'Tighassaline', 'region_id'=>5],
                ['city'=>  'Tighza', 'region_id'=>5],
                ['city'=>  'Timahdite', 'region_id'=>3],
                ['city'=>  'Tinejdad', 'region_id'=>8],
                ['city'=>  'Tizguite', 'region_id'=>3],
                ['city'=>  'Toulal', 'region_id'=>3],
                ['city'=>  'Tounfite', 'region_id'=>8],
                ['city'=>  'Zaouia dIfrane', 'region_id'=>3],
                ['city'=>  'Zaïda', 'region_id'=>8],
                ['city'=>  'Ahfir', 'region_id'=>2],
                ['city'=>  'Aklim', 'region_id'=>2],
                ['city'=>  'Al Aroui', 'region_id'=>2],
                ['city'=>  'Aïn Bni Mathar', 'region_id'=>2],
                ['city'=>  'Aïn Erreggada', 'region_id'=>2],
                ['city'=>  'Ben Taïeb', 'region_id'=>2],
                ['city'=>  'Berkane', 'region_id'=>2],
                ['city'=>  'Bni Ansar', 'region_id'=>2],
                ['city'=>  'Bni Chiker', 'region_id'=>2],
                ['city'=>  'Bni Drar', 'region_id'=>2],
                ['city'=>  'Bni Tadjite', 'region_id'=>2],
                ['city'=>  'Bouanane', 'region_id'=>2],
                ['city'=>  'Bouarfa', 'region_id'=>2],
                ['city'=>  'Bouhdila', 'region_id'=>2],
                ['city'=>  'Dar El Kebdani', 'region_id'=>2],
                ['city'=>  'Debdou', 'region_id'=>2],
                ['city'=>  'Douar Kannine', 'region_id'=>2],
                ['city'=>  'Driouch', 'region_id'=>2],
                ['city'=>  'El Aïoun Sidi Mellouk', 'region_id'=>2],
                ['city'=>  'Farkhana', 'region_id'=>2],
                ['city'=>  'Figuig', 'region_id'=>2],
                ['city'=>  'Ihddaden', 'region_id'=>2],
                ['city'=>  'Jaâdar', 'region_id'=>2],
                ['city'=>  'Jerada', 'region_id'=>2],
                ['city'=>  'Kariat Arekmane', 'region_id'=>2],
                ['city'=>  'Kassita', 'region_id'=>2],
                ['city'=>  'Kerouna', 'region_id'=>2],
                ['city'=>  'Laâtamna', 'region_id'=>2],
                ['city'=>  'Madagh', 'region_id'=>2],
                ['city'=>  'Midar', 'region_id'=>2],
                ['city'=>  'Nador', 'region_id'=>2],
                ['city'=>  'Naima', 'region_id'=>2],
                ['city'=>  'Oued Heimer', 'region_id'=>2],
                ['city'=>  'Oujda', 'region_id'=>2],
                ['city'=>  'Ras El Ma', 'region_id'=>2],
                ['city'=>  'Saïdia', 'region_id'=>2],
                ['city'=>  'Selouane', 'region_id'=>2],
                ['city'=>  'Sidi Boubker', 'region_id'=>2],
                ['city'=>  'Sidi Slimane Echcharaa', 'region_id'=>2],
                ['city'=>  'Talsint', 'region_id'=>2],
                ['city'=>  'Taourirt', 'region_id'=>2],
                ['city'=>  'Tendrara', 'region_id'=>2],
                ['city'=>  'Tiztoutine', 'region_id'=>2],
                ['city'=>  'Touima', 'region_id'=>2],
                ['city'=>  'Touissit', 'region_id'=>2],
                ['city'=>  'Zaïo', 'region_id'=>2],
                ['city'=>  'Zeghanghane', 'region_id'=>2],
                ['city'=>  'Rabat', 'region_id'=>4],
                ['city'=>  'Salé', 'region_id'=>4],
                ['city'=>  'Ain El Aouda', 'region_id'=>4],
                ['city'=>  'Harhoura', 'region_id'=>4],
                ['city'=>  'Khémisset', 'region_id'=>4],
                ['city'=>  'Oulmès', 'region_id'=>4],
                ['city'=>  'Rommani', 'region_id'=>4],
                ['city'=>  'Sidi Allal El Bahraoui', 'region_id'=>4],
                ['city'=>  'Sidi Bouknadel', 'region_id'=>4],
                ['city'=>  'Skhirate', 'region_id'=>4],
                ['city'=>  'Tamesna', 'region_id'=>4],
                ['city'=>  'Témara', 'region_id'=>4],
                ['city'=>  'Tiddas', 'region_id'=>4],
                ['city'=>  'Tiflet', 'region_id'=>4],
                ['city'=>  'Touarga', 'region_id'=>4],
                ['city'=>  'Agadir', 'region_id'=>9],
                ['city'=>  'Agdz', 'region_id'=>8],
                ['city'=>  'Agni Izimmer', 'region_id'=>9],
                ['city'=>  'Aït Melloul', 'region_id'=>9],
                ['city'=>  'Alnif', 'region_id'=>8],
                ['city'=>  'Anzi', 'region_id'=>9],
                ['city'=>  'Aoulouz', 'region_id'=>9],
                ['city'=>  'Aourir', 'region_id'=>9],
                ['city'=>  'Arazane', 'region_id'=>9],
                ['city'=>  'Aït Baha', 'region_id'=>9],
                ['city'=>  'Aït Iaâza', 'region_id'=>9],
                ['city'=>  'Aït Yalla', 'region_id'=>8],
                ['city'=>  'Ben Sergao', 'region_id'=>9],
                ['city'=>  'Biougra', 'region_id'=>9],
                ['city'=>  'Boumalne-Dadès', 'region_id'=>8],
                ['city'=>  'Dcheira El Jihadia', 'region_id'=>9],
                ['city'=>  'Drargua', 'region_id'=>9],
                ['city'=>  'El Guerdane', 'region_id'=>9],
                ['city'=>  'Harte Lyamine', 'region_id'=>8],
                ['city'=>  'Ida Ougnidif', 'region_id'=>9],
                ['city'=>  'Ifri', 'region_id'=>8],
                ['city'=>  'Igdamen', 'region_id'=>9],
                ['city'=>  'Ighil nOumgoun', 'region_id'=>8],
                ['city'=>  'Imassine', 'region_id'=>8],
                ['city'=>  'Inezgane', 'region_id'=>9],
                ['city'=>  'Irherm', 'region_id'=>9],
                ['city'=>  'Kelaat-MGouna', 'region_id'=>8],
                ['city'=>  'Lakhsas', 'region_id'=>9],
                ['city'=>  'Lakhsass', 'region_id'=>9],
                ['city'=>  'Lqliâa', 'region_id'=>9],
                ['city'=>  'Msemrir', 'region_id'=>8],
                ['city'=>  'Massa city laroc)', 'region_id'=>9],
                ['city'=>  'Megousse', 'region_id'=>9],
                ['city'=>  'Ouarzazate', 'region_id'=>8],
                ['city'=>  'Oulad Berhil', 'region_id'=>9],
                ['city'=>  'Oulad Teïma', 'region_id'=>9],
                ['city'=>  'Sarghine', 'region_id'=>8],
                ['city'=>  'Sidi Ifni', 'region_id'=>10],
                ['city'=>  'Skoura', 'region_id'=>8],
                ['city'=>  'Tabounte', 'region_id'=>8],
                ['city'=>  'Tafraout', 'region_id'=>9],
                ['city'=>  'Taghzout', 'region_id'=>1],
                ['city'=>  'Tagzen', 'region_id'=>9],
                ['city'=>  'Taliouine', 'region_id'=>9],
                ['city'=>  'Tamegroute', 'region_id'=>8],
                ['city'=>  'Tamraght', 'region_id'=>9],
                ['city'=>  'Tanoumrite Nkob Zagora', 'region_id'=>8],
                ['city'=>  'Taourirt ait zaghar', 'region_id'=>8],
                ['city'=>  'Taroudannt', 'region_id'=>9],
                ['city'=>  'Temsia', 'region_id'=>9],
                ['city'=>  'Tifnit', 'region_id'=>9],
                ['city'=>  'Tisgdal', 'region_id'=>9],
                ['city'=>  'Tiznit', 'region_id'=>9],
                ['city'=>  'Toundoute', 'region_id'=>8],
                ['city'=>  'Zagora', 'region_id'=>8],
                ['city'=>  'Afourar', 'region_id'=>5],
                ['city'=>  'Aghbala', 'region_id'=>5],
                ['city'=>  'Azilal', 'region_id'=>5],
                ['city'=>  'Aït Majden', 'region_id'=>5],
                ['city'=>  'Beni Ayat', 'region_id'=>5],
                ['city'=>  'Béni Mellal', 'region_id'=>5],
                ['city'=>  'Bin elouidane', 'region_id'=>5],
                ['city'=>  'Bradia', 'region_id'=>5],
                ['city'=>  'Bzou', 'region_id'=>5],
                ['city'=>  'Dar Oulad Zidouh', 'region_id'=>5],
                ['city'=>  'Demnate', 'region_id'=>5],
                ['city'=>  'Draa', 'region_id'=>8],
                ['city'=>  'El Ksiba', 'region_id'=>5],
                ['city'=>  'Foum Jamaa', 'region_id'=>5],
                ['city'=>  'Fquih Ben Salah', 'region_id'=>5],
                ['city'=>  'Kasba Tadla', 'region_id'=>5],
                ['city'=>  'Ouaouizeght', 'region_id'=>5],
                ['city'=>  'Oulad Ayad', 'region_id'=>5],
                ['city'=>  'Oulad MBarek', 'region_id'=>5],
                ['city'=>  'Oulad Yaich', 'region_id'=>5],
                ['city'=>  'Sidi Jaber', 'region_id'=>5],
                ['city'=>  'Souk Sebt Oulad Nemma', 'region_id'=>5],
                ['city'=>  'Zaouïat Cheikh', 'region_id'=>5],
                ['city'=>  'Tanger‎', 'region_id'=>1],
                ['city'=>  'Tétouan‎', 'region_id'=>1],
                ['city'=>  'Akchour', 'region_id'=>1],
                ['city'=>  'Assilah', 'region_id'=>1],
                ['city'=>  'Bab Berred', 'region_id'=>1],
                ['city'=>  'Bab Taza', 'region_id'=>1],
                ['city'=>  'Brikcha', 'region_id'=>1],
                ['city'=>  'Chefchaouen', 'region_id'=>1],
                ['city'=>  'Dar Bni Karrich', 'region_id'=>1],
                ['city'=>  'Dar Chaoui', 'region_id'=>1],
                ['city'=>  'Fnideq', 'region_id'=>1],
                ['city'=>  'Gueznaia', 'region_id'=>1],
                ['city'=>  'Jebha', 'region_id'=>1],
                ['city'=>  'Karia', 'region_id'=>3],
                ['city'=>  'Khémis Sahel', 'region_id'=>1],
                ['city'=>  'Ksar El Kébir', 'region_id'=>1],
                ['city'=>  'Larache', 'region_id'=>1],
                ['city'=>  'Mdiq', 'region_id'=>1],
                ['city'=>  'Martil', 'region_id'=>1],
                ['city'=>  'Moqrisset', 'region_id'=>1],
                ['city'=>  'Oued Laou', 'region_id'=>1],
                ['city'=>  'Oued Rmel', 'region_id'=>1],
                ['city'=>  'Ouazzane', 'region_id'=>1],
                ['city'=>  'Point Cires', 'region_id'=>1],
                ['city'=>  'Sidi Lyamani', 'region_id'=>1],
                ['city'=>  'Sidi Mohamed ben Abdallah el-Raisuni', 'region_id'=>1],
                ['city'=>  'Zinat', 'region_id'=>1],
                ['city'=>  'Ajdir‎', 'region_id'=>1],
                ['city'=>  'Aknoul‎', 'region_id'=>3],
                ['city'=>  'Al Hoceïma‎', 'region_id'=>1],
                ['city'=>  'Aït Hichem‎', 'region_id'=>1],
                ['city'=>  'Bni Bouayach‎', 'region_id'=>1],
                ['city'=>  'Bni Hadifa‎', 'region_id'=>1],
                ['city'=>  'Ghafsai‎', 'region_id'=>3],
                ['city'=>  'Guercif‎', 'region_id'=>2],
                ['city'=>  'Imzouren‎', 'region_id'=>1],
                ['city'=>  'Inahnahen‎', 'region_id'=>1],
                ['city'=>  'Issaguen city letama)‎', 'region_id'=>1],
                ['city'=>  'Karia city lJadida)‎', 'region_id'=>6],
                ['city'=>  'Karia Ba Mohamed‎', 'region_id'=>3],
                ['city'=>  'Oued Amlil‎', 'region_id'=>3],
                ['city'=>  'Oulad Zbair‎', 'region_id'=>3],
                ['city'=>  'Tahla‎', 'region_id'=>3],
                ['city'=>  'Tala Tazegwaght‎', 'region_id'=>1],
                ['city'=>  'Tamassint‎', 'region_id'=>1],
                ['city'=>  'Taounate‎', 'region_id'=>3],
                ['city'=>  'Targuist‎', 'region_id'=>1],
                ['city'=>  'Taza‎', 'region_id'=>3],
                ['city'=>  'Taïnaste‎', 'region_id'=>3],
                ['city'=>  'Thar Es-Souk‎', 'region_id'=>3],
                ['city'=>  'Tissa‎', 'region_id'=>3],
                ['city'=>  'Tizi Ouasli‎', 'region_id'=>3],
                ['city'=>  'Laayoune‎', 'region_id'=>11],
                ['city'=>  'El Marsa‎', 'region_id'=>11],
                ['city'=>  'Tarfaya‎', 'region_id'=>11],
                ['city'=>  'Boujdour‎', 'region_id'=>11],
                ['city'=>  'Awsard', 'region_id'=>12],
                ['city'=>  'Oued-Eddahab', 'region_id'=>12],
                ['city'=>  'Stehat', 'region_id'=>1],
                ['city'=>  'Ait Attab','region_id' => 5],

        ]);
    }
}
